//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusteriBilgiSistemi.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public Musteriler()
        {
            this.Cariler = new HashSet<Cariler>();
            this.Sepet = new HashSet<Sepet>();
        }
    
        public int MusteriId { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriSoyadi { get; set; }
        public string FirmaAdi { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Onay { get; set; }
    
        public virtual ICollection<Cariler> Cariler { get; set; }
        public virtual ICollection<Sepet> Sepet { get; set; }
    }
}
