//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusteriBilgiSistemi.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemeTuru
    {
        public OdemeTuru()
        {
            this.Sepet = new HashSet<Sepet>();
        }
    
        public int TurId { get; set; }
        public string OdemeAdi { get; set; }
        public Nullable<bool> Onay { get; set; }
    
        public virtual ICollection<Sepet> Sepet { get; set; }
    }
}
