//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusteriBilgiSistemi.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.SepetDetay = new HashSet<SepetDetay>();
        }
    
        public int ProductId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<short> UnitInStock { get; set; }
        public Nullable<bool> Onay { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<SepetDetay> SepetDetay { get; set; }
    }
}
