//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusteriBilgiSistemi.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int SepetId { get; set; }
        public int MusteriId { get; set; }
        public Nullable<int> OdemeTipId { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<bool> Onay { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual OdemeTuru OdemeTuru { get; set; }
        public virtual SepetDetay SepetDetay { get; set; }
    }
}
