//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusteriBilgiSistemi.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SepetDetay
    {
        public SepetDetay()
        {
            this.Sepet = new HashSet<Sepet>();
        }
    
        public int SepetDetayId { get; set; }
        public Nullable<int> SepetId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<bool> Onay { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual ICollection<Sepet> Sepet { get; set; }
    }
}
